# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "artifact" ]
  pull_request:
    branches: [ "artifact" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      artifact-tag: ${{ steps.changelog.outputs.version }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.18.0
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.2.1
      with:
        arguments: build
        
    - name: Tag artifact
      run: mv build/libs/greetings-ci.jar build/libs/greetings-ci-${{ steps.changelog.outputs.version || github.event.inputs.myVersion }}.jar
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: greetings-jar
        path: |
          build/libs
          test-script.sh

test-run:
  runs-on: ubuntu-latest
  needs: build
  
  steps:
  - name: Download candidate artifacts
    uses: actions/download-artifact@v3 
    with:
    name: greetings-jar
 
  - name: Execute test
    shell: bash
  run: | 
    chmod +x ./test-script.sh
    ./test-script.sh ${{ needs.build.outputs.artifact-tag || github.event.inputs.myVersion }} ${{ github.event.inputs.myValues }
